channels:
  - conda-forge
  - main
dependencies:
  - abseil-cpp=20200225.2
  - appdirs=1.4.4
  - appnope=0.1.0
  - arrow-cpp=2.0.0
  - attrs=20.3.0
  - aws-c-common=0.4.59
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.10
  - aws-sdk-cpp=1.8.70
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - beautifulsoup4=4.9.3
  - black=20.8b1
  - boto3=1.16.23
  - botocore=1.19.23
  - brotli=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2020.11.8
  - certifi=2020.11.8
  - cffi=1.14.3
  - cfgv=3.2.0
  - chardet=3.0.4
  - click=7.1.2
  - codecov=2.1.10
  - coverage=5.3
  - cryptography=3.2.1
  - dataclasses=0.7
  - decorator=4.4.2
  - dill=0.3.3
  - distlib=0.3.1
  - dnslib=0.9.14
  - dnspython=2.0.0
  - docopt=0.6.2
  - easyprocess=0.3
  - editdistance=0.5.3
  - filelock=3.0.12
  - freetype=2.10.4
  - fsspec=0.8.4
  - geckodriver=0.28.0
  - gettext=0.19.8.1
  - gflags=2.2.2
  - glog=0.4.0
  - grpc-cpp=1.33.2
  - icu=67.1
  - identify=1.5.10
  - idna=2.10
  - iniconfig=1.1.1
  - ipython=7.19.0
  - ipython_genutils=0.2.0
  - jedi=0.17.2
  - jmespath=0.10.0
  - jpeg=9d
  - krb5=1.17.2
  - lcms2=2.11
  - leveldb=1.22
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.71.1
  - libcxx=11.0.0
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.2.1
  - libgfortran=5.0.0
  - libgfortran5=9.3.0
  - libiconv=1.16
  - libidn2=2.3.0
  - liblapack=3.9.0
  - libnghttp2=1.41.0
  - libopenblas=0.3.12
  - libpng=1.6.37
  - libprotobuf=3.13.0.1
  - libssh2=1.9.0
  - libthrift=0.13.0
  - libtiff=4.1.0
  - libunistring=0.9.10
  - libutf8proc=2.5.0
  - libuv=1.40.0
  - libwebp-base=1.1.0
  - llvm-openmp=11.0.0
  - localstack=0.11.1.1
  - localstack-client=1.4
  - localstack-ext=0.11.14.3
  - lz4-c=1.9.2
  - more-itertools=8.6.0
  - multiprocess=0.70.11.1
  - mypy_extensions=0.4.3
  - ncurses=6.2
  - nodeenv=1.5.0
  - nodejs=14.14.0
  - numpy=1.19.4
  - olefile=0.46
  - openssl=1.1.1h
  - orc=1.6.5
  - packaging=20.4
  - pandas=1.1.4
  - parquet-cpp=1.5.1
  - parso=0.7.1
  - pathspec=0.8.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.0.1
  - pip=20.2.4
  - pluggy=0.13.1
  - pre-commit=2.8.2
  - prompt-toolkit=3.0.8
  - psutil=5.7.3
  - ptyprocess=0.6.0
  - py=1.9.0
  - pyaes=1.6.1
  - pyarrow=2.0.0
  - pycparser=2.20
  - pygments=2.7.2
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pysocks=1.7.1
  - pytest=6.1.2
  - pytest-cov=2.10.1
  - python=3.8.6
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2020.4
  - pyvirtualdisplay=0.2.5
  - pyyaml=5.3.1
  - re2=2020.11.01
  - readline=8.0
  - redis-py=3.5.3
  - regex=2020.11.13
  - requests=2.25.0
  - s3fs=0.4.0
  - s3transfer=0.3.3
  - selenium=3.141.0
  - sentry-sdk=0.19.4
  - setuptools=49.6.0
  - six=1.15.0
  - snappy=1.1.8
  - soupsieve=2.0.1
  - sqlite=3.33.0
  - tabulate=0.8.7
  - tblib=1.6.0
  - tk=8.6.10
  - toml=0.10.2
  - traitlets=5.0.5
  - typed-ast=1.4.1
  - typing_extensions=3.7.4.3
  - urllib3=1.25.11
  - virtualenv=20.2.1
  - wcwidth=0.2.5
  - wget=1.20.1
  - wheel=0.35.1
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - amazon-kclpy==2.0.1
    - argparse==1.4.0
    - aws-sam-translator==1.30.1
    - aws-xray-sdk==2.6.0
    - boto==2.49.0
    - cfn-lint==0.41.0
    - crontab==0.22.9
    - dataclasses-json==0.5.2
    - docker==4.4.0
    - domain-utils==0.7.1
    - ecdsa==0.16.1
    - flask==1.1.2
    - flask-cors==3.0.9
    - future==0.18.2
    - importlib-metadata==3.0.0
    - itsdangerous==1.1.0
    - jinja2==2.11.2
    - jsondiff==1.2.0
    - jsonpatch==1.26
    - jsonpickle==1.4.1
    - jsonpointer==2.0
    - jsonschema==3.2.0
    - junit-xml==1.9
    - markupsafe==1.1.1
    - marshmallow==3.9.1
    - marshmallow-enum==1.5.1
    - mock==4.0.2
    - moto-ext==1.3.15.15
    - networkx==2.5
    - plyvel==1.3.0
    - pyasn1==0.4.8
    - pyrsistent==0.17.3
    - python-jose==3.2.0
    - requests-file==1.5.1
    - responses==0.12.1
    - rsa==4.6
    - sshpubkeys==3.1.0
    - stringcase==1.2.0
    - subprocess32==3.5.4
    - tldextract==2.2.2
    - typing-inspect==0.6.0
    - websocket-client==0.57.0
    - werkzeug==1.0.1
    - wrapt==1.12.1
    - xmltodict==0.12.0
    - zipp==3.4.0
name: openwpm